cursor #e0e2ef
cursor_text_color #c3c6d3

foreground            #e0e2ef
background            #10131c
selection_foreground  #2b2e4d
selection_background  #c2c3eb
url_color             #afc6ff

color0   #10131c
color1   #ff7299
color2   #7fff93
color3   #fff872
color4   #97b1f2
color5   #324576
color6   #afc6ff
color7   #eff3ff
color8   #999ca5
color9   #ff9fb9
color10  #a5ffb3
color11  #fffaa5
color12  #bbceff
color13  #c7d7ff
color14  #dbe5ff
color15  #f8faff
