cursor #1d1b20
cursor_text_color #49454e

foreground            #1d1b20
background            #fef7ff
selection_foreground  #ffffff
selection_background  #625b71
url_color             #6750a4

color0   #141218
color1   #9b3c4f
color2   #297b3a
color3   #c49d2d
color4   #684fac
color5   #e0d5ff
color6   #6750A4
color7   #2c2c2d
color8   #88878b
color9   #c46074
color10  #4eb464
color11  #d5ad3c
color12  #7a5cc7
color13  #e0d5ff
color14  #ad9ed5
color15  #f2f0f6
