cursor #ecdeec
cursor_text_color #cfc3d0

foreground            #ecdeec
background            #18111a
selection_foreground  #422741
selection_background  #e1bbdc
url_color             #e8b3ff

color0   #18111a
color1   #ff7288
color2   #7fff9f
color3   #ffdc72
color4   #d89bf2
color5   #623576
color6   #e8b3ff
color7   #faefff
color8   #a199a5
color9   #ff9fae
color10  #a5ffbc
color11  #ffe9a5
color12  #ebbeff
color13  #eec9ff
color14  #f4dcff
color15  #fdf8ff
