[main]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\t\xe7\0\0\x3\xf3\0\0\0\0\0\0\0\0\0\0\t\xe7\0\0\x3\xf3\0\0\0\0\0\0\0\0\n\0\0\0\0\0\0\0\0\0\0\0\t\xe7\0\0\x3\xf3)
windowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\t\xe8\0\0\x3\xde\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\0)

[notification]
app=true
donation_message=false
show_msg=true
show_name=true
show_photo=true

[onboarding]
completed=true
last_environment=local
version=2

[system]
quit_in_close=false
spellCheckers=true
start_background=false
start_system=false
theme=dark
tray_icon=true
tray_theme=symbolic_light
wayland=false

[website]
open_page=false
